program: main.py
entity: wilderlavington
method: grid
project: TargetBasedSurrogateOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  min_epochs:
    values:
    - 500
  algo:
    values:
    - SGD_FMDOpt
    - SLS_FMDOpt
    - Ada_FMDOpt
    - Diag_Ada_FMDOpt
  normalize_epochs_lengths:
    values:
    - 1
  seed:
    values:
    - 1
    - 2
    - 3
  fullbatch:
    values:
    - 1

  outer_c:
    values:
    - 0.5
  m:
    values:
    - 1
    - 10
    - 100
    - 1000
  use_optimal_stepsize:
    values:
    - 0
  log_lr:
    values:
    - -3.
    - -2.
    - -1.
    - 0.0
    - 1.
    - 2.
    - 3.
  loss:
    values:
    - MSELoss
  dataset_name:
    values:
    - mfac
    - mfac0
    - mfac1
    - mfac4
  eta_schedule:
    values:
    - constant
