program: main.py
entity: wilderlavington
method: grid
project: TargetBasedSurrogateOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  min_epochs:
    values:
    - 500
  algo:
    values:
    - SVRG
  normalize_epochs_lengths:
    values:
    - 1
  seed:
    values:
    - 1
    - 2
    - 3
  use_optimal_stepsize:
    values:
    - 1 
  batch_size:
    values: 
    - 25
    - 125
    - 625
  label:
    values:
    - 'svmlib'
  loss:
    values:
    - MSELoss
    - BCEWithLogitsLoss
  dataset_name:
    values:
    - mushrooms
    - ijcnn
    - rcv1
  c:
    values:
    - 0.5
  eta_schedule:
    values:
    - constant